name: robinson
favicon: null
layout_spectrum: 0.5929063053335994
typography_spectrum: 0.043384711956605315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3178129175212234
  lightness: 0.1273003772366792
  saturation: 0.1048424995969981
  rhythmicContrast: 0.08172165579162538
purpose: []
